image: gcc

before_script:
  - apt-get update -qq && apt-get install -y -qq libcunit1 libcunit1-dev

stages:
  - build
  - test

build:
  stage: build
  script:
    - make all
 
test:
  stage: test
  script:
    - make test
    - make coverage


